routes/web.php
<?php

use App\Models\Job;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $jobs = Job::active()->orderBy('updated_at','DESC');
    return view('pages.index', compact('jobs'));
})->name('home');

Route::get('/about', function () {
    return view('pages.about');
})->name('about');

Route::get('/contact', function () {
    return view('pages.contact');
})->name('contact');

Route::post('contact-send','App\Http\Controllers\ContactController@sendMail')->name('contact.send');


Auth::routes();

Route::prefix('jobs')->name('jobs.')->group( function () {
    Route::get('/','App\Http\Controllers\JobController@index')->name('home');
    Route::get('/{job}','App\Http\Controllers\JobController@show')->name('show');
    Route::post('/','App\Http\Controllers\JobController@searchJobs')->name('search');
    Route::get('/applied','App\Http\Controllers\JobController@applied')->name('applied');
});

Route::get('/home','App\Http\Controllers\HomeController@index');
Route::prefix('dashboard')->middleware('auth')->name('dashboard.')->group(function(){
    Route::get('/profile/{user}','App\Http\Controllers\AdminController@userProfile')->name('profile.user');
    Route::get('/profile','App\Http\Controllers\AccountController@index')->name('profile.user');
    Route::patch('/profile/update/{user}','App\Http\Controllers\AccountController@profileUpdate')->name('profile.update');
    Route::get('/become/employee','App\Http\Controllers\EmployeeController@create')->name('become.employee');
    Route::post('/become/employee','App\Http\Controllers\EmployeeController@store')->name('become.employee');
    Route::get('/change-password','App\Http\Controllers\AdminController@cPassword')->name('change.password');
    Route::get('/deactivate/{user}','App\Http\Controllers\AccountController@deactivate')->name('deactivate.account');
    //User Leaves Route
    Route::get('/leaves','App\Http\Controllers\LeaveController@index')->name('leaves.applied');
    Route::get('/leave/delete/{leave}','App\Http\Controllers\LeaveController@destroy')->name('leave.delete');
    Route::post('/leave/apply','App\Http\Controllers\LeaveController@store')->name('leave.apply');

    Route::post('/password/change','App\Http\Controllers\AdminController@changePassword')->name('password.change');
    Route::get('/','App\Http\Controllers\AdminController@index')->name('home');

        Route::get('/jobs/applied','App\Http\Controllers\JobController@applied')->name('jobs.applied');
        Route::get('/jobs','App\Http\Controllers\JobAssignedController@index')->name('jobs.assigned');
        Route::get('/jobs/assigned/delete/{jobAssigned}','App\Http\Controllers\JobAssignedController@destroy')->name('jobs.assigned.delete');
        Route::get('/jobs/applied/delete/{jobApplication}','App\Http\Controllers\JobController@jobAppDestroy')->name('jobs.applied.delete');
        Route::post('/jobs/apply/{job}','App\Http\Controllers\JobController@jobApply')->name('jobs.apply');
        Route::get('/account/settings','App\Http\Controllers\AccountController@settings')->name('account.settings');
        Route::post('/bank/store','App\Http\Controllers\AccountController@bankDetails')->name('bank.store');
        Route::post('/document/store','App\Http\Controllers\AccountController@documentUpload')->name('document.store');

    Route::prefix('admin')->name('admin.')->middleware('can:admin')->group(function(){
        Route::get('/','App\Http\Controllers\AdminController@adminHome')->name('home');

        // Admin Leave Routes
        Route::get('/leaves','App\Http\Controllers\LeaveController@adminLeaves')->name('leaves');
        Route::get('/leave/reject/{leave}','App\Http\Controllers\LeaveController@rejectLeave')->name('leave.reject');
        Route::get('/leave/accept/{leave}','App\Http\Controllers\LeaveController@acceptLeave')->name('leave.accept');

        Route::get('/company','App\Http\Controllers\CompanyController@index')->name('company');
        Route::post('/company/save','App\Http\Controllers\CompanyController@store')->name('company.save');
        Route::post('/company/logo/upload','App\Http\Controllers\CompanyController@uploadImage')->name('company.logo.upload');
        Route::prefix('employees')->name('employees.')->group(function(){
            Route::get('/','App\Http\Controllers\AdminController@employees')->name('home');
            Route::get('/delete/{employee}','App\Http\Controllers\AdminController@employeeDestroy')->name('delete');
            Route::get('/{employee}','App\Http\Controllers\AdminController@employee')->name('show');
        });
        Route::prefix('users')->name('users.')->group(function(){
            Route::get('/','App\Http\Controllers\AdminController@users')->name('home');
            Route::post('/store','App\Http\Controllers\AdminController@userSave')->name('store');
            Route::get('/add','App\Http\Controllers\AdminController@userAdd')->name('add');
            Route::patch('/update/{user}','App\Http\Controllers\AdminController@userUpdate')->name('update');
            Route::get('/edit/{user}','App\Http\Controllers\AdminController@userAdd')->name('edit');
            Route::get('/delete/{user}','App\Http\Controllers\AdminController@userDestroy')->name('delete');
            Route::get('/activate/{user}','App\Http\Controllers\AdminController@userActivate')->name('activate');
            Route::get('/deactivate/{user}','App\Http\Controllers\AdminController@userDeactivate')->name('deactivate');
        });
        Route::prefix('category')->name('category.')->group(function(){
            Route::get('/','App\Http\Controllers\AdminController@category')->name('home');
            Route::post('/store','App\Http\Controllers\AdminController@categorySave')->name('store');
            Route::get('/add','App\Http\Controllers\AdminController@categoryAdd')->name('add');
            Route::patch('/update/{jobCategory}','App\Http\Controllers\AdminController@categoryUpdate')->name('update');
            Route::get('/edit/{jobCategory}','App\Http\Controllers\AdminController@categoryAdd')->name('edit');
            Route::get('/delete/{jobCategory}','App\Http\Controllers\AdminController@categoryDestroy')->name('delete');
        });
        Route::prefix('jobs')->name('jobs.')->group(function(){
            Route::get('/','App\Http\Controllers\AdminController@jobs')->name('home');
            Route::get('/add','App\Http\Controllers\AdminController@jobAdd')->name('add');
            Route::post('/store','App\Http\Controllers\AdminController@jobSave')->name('store');
            Route::patch('/update/{job}','App\Http\Controllers\AdminController@jobUpdate')->name('update');
            Route::get('/edit/{job}','App\Http\Controllers\AdminController@jobAdd')->name('edit');
            Route::get('/delete/{job}','App\Http\Controllers\AdminController@jobDestroy')->name('delete');
            Route::get('/applications','App\Http\Controllers\AdminController@applications')->name('applications');
            Route::get('/{job}/applications','App\Http\Controllers\AdminController@jobApplications')->name('applications.specific');
            Route::get('/applications/delete/{jobApplication}','App\Http\Controllers\AdminController@jobAppDestroy')->name('applications.delete');
            Route::get('/applications/accept/{jobApplication}','App\Http\Controllers\AdminController@jobAppAccept')->name('applications.accept');
            Route::get('/applications/reject/{jobApplication}','App\Http\Controllers\AdminController@jobAppReject')->name('applications.reject');
            Route::get('/candidates','App\Http\Controllers\AdminController@jobCandidates')->name('candidates');
        });
    });
});

Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;
    protected $primaryKey = 'user_id';
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'fname', 'mname', 'lname', 'email', 'password', 'tel', 'hear',  'gender', 'password', 'status', 'level',
    ];




    public function roles(){
        return $this->belongsToMany(Role::class, 'role_user', 'user_id');
    }
    public function employee(){
        return $this->hasOne('App\Models\Employee', 'user_id');
    }
    public function jobassigned(){
        return $this->hasMany('App\Models\JobAssigned', 'user_id');
    }
    public function application()
    {
        return $this->hasMany('App\Models\JobApplication', 'user_id');
    }

    public function job(){
        return $this->hasMany('App\Models\Job', 'user_id');
    }

    public function leave(){
        return $this->hasMany('App\Models\Leave', 'user_id');
    }
    public function education(){
        return $this->hasMany('App\Models\EmployeeEducation', 'user_id');
    }
    public function work_history(){
        return $this->hasMany('App\Models\EmployeeWorkHistory', 'user_id');
    }
    public function reference(){
        return $this->hasMany('App\Models\EmployeeReference', 'user_id');
    }

    public function bank(){
        return $this->hasOne('App\Models\BankDetails', 'user_id');
    }

    public function documents(){
        return $this->hasOne('App\Models\EmployeeDocuments', 'user_id');
    }

    public function company(){
        return $this->hasOne('App\Models\Company', 'user_id');
    }

    public function name()
    {
        return $this->fname.' '.$this->mname.' '.$this->lname;
    }

    public function isOwner($owner)
    {
        if ($this->user_id == $owner) {
            return true;
        }else{
            return false;
        }
    }

    public function avatar(){
        if ($this->gender == 'm') {
            return asset('/avatars/male.png');
        } else {
            return asset('/avatars/female.png');
        }
    }
    public static function Role()
    {
        # code...
        if(\Auth::user()){
            $role = \Auth::user()->user_level;
            return $role;
        }else{
            return false;
        }
    }
    public function isAdmin()
    {
        # code...
        if(\Auth::check()){
            if (\Auth::user()->level == 1) {
                return true;
            } else {
                return false;
            }
        }else{
            return false;
        }
    }
    public function isEmployee()
    {
        # code...
        if(\Auth::check()){
            if ($this->isAdmin()) {
                return true;
            }else{
                if (\Auth::user()->level == 0 && \Auth::user()->employee()->exists()) {
                    return true;
                } else {
                    return false;
                }
            }
        }else{
            return false;
        }
    }
    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function isSuper()
    {
        if ($this->level > 1){
            return true;
        }
        return false;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function dashboard()
    {
        return view('users.index');
    }

    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
}

resources/views/users/account.blade.php
@extends('layouts.master')
@section('title', 'Account Settiings')
@section('content')
@include('inc.dash-bread')
<section>
    <div class="block no-padding">
        <div class="container">
             <div class="row no-gape">
                 @include('inc.sidebar')
                 <div class="col-lg-9 column">
                     <div class="padding-left">
                         <div class="manage-jobs-sec">
                             <div class="change-password">

                                 <form class="needs-validation col-md-6" method="POST" action="{{ route('dashboard.bank.store') }}">

                                     <div class="row">
                                         <div class="col-md-12 mt-2"><h4>Bank Details</h4></div>
                                         @csrf
                                         <div class="col-md-12">
                                             <span class="pf-title">Account Name*</span>
                                             <div class="pf-field">
                                                 <input type="text" value="{{ old('account_name', $bank->account_name) }}" name="account_name" required/>
                                             </div>
                                         </div>
                                         <div class="col-md-12">
                                             <span class="pf-title">Account Number*</span>
                                             <div class="pf-field">
                                                 <input type="text" value="{{ old('account_number', $bank->account_number) }}" name="account_number" required/>
                                             </div>
                                         </div>
                                         <div class="col-md-12">
                                             <span class="pf-title">Bank Name*</span>
                                             <div class="pf-field">
                                                 <input type="text" value="{{ old('bank_name', $bank->bank_name) }}" name="bank_name" required/>
                                             </div>
                                         </div>
                                         <div class="col-md-12">
                                             <span class="pf-title">Bank Routing Number*</span>
                                             <div class="pf-field">
                                                 <input type="text" value="{{ old('routing_number', $bank->routing_number) }}" name="routing_number" required/>
                                             </div>
                                         </div>
                                         <div class="col-md-12 mb-5">
                                             <button type="submit">Save</button>
                                         </div>
                                     </div>
                                 </form>
                                 <form class="needs-validation col-md-6" method="POST" action="{{ route('dashboard.document.store') }}" enctype="multipart/form-data">

                                     <div class="row">
                                         <div class="col-md-12 mt-2"><h4>My Documents</h4></div>
                                         @csrf
                                         <div class="col-md-12">
                                             <span class="pf-title">Resume<span class="text-danger">*</span></span>
                                             <div class="pf-field">
                                                 <input type="file" value="{{ old('resume', $doc->resume) }}" name="resume" />
                                             </div>
                                         </div>
                                         <div class="col-md-12">
                                             <span class="pf-title">SSN Card<span class="text-danger">*</span></span>
                                             <div class="pf-field">
                                                 <input type="file" value="{{ old('ssn', $doc->ssn) }}" name="ssn" />
                                             </div>
                                         </div>
                                         <div class="col-md-12">
                                             <span class="pf-title">Valid ID Card<span class="text-danger">*</span></span>
                                             <div class="pf-field">
                                                 <input type="file" value="{{ old('id', $doc->id) }}" name="id" />
                                             </div>
                                         </div>
                                         <div class="col-md-12">
                                             <span class="pf-title">Passport<span class="text-danger">*</span></span>
                                             <div class="pf-field">
                                                 <input type="file" value="{{ old('passport', $doc->passport) }}" name="passport" />
                                             </div>
                                         </div>
                                         <div class="col-md-12 mb-5">
                                             <button type="submit">Upload</button>
                                         </div>
                                     </div>
                                 </form>
                                 <div class="col-12">
                                    <div class="container">
                                        <h4>Deactivate Account</h4>
                                        <a href="{{ route('dashboard.deactivate.account', \Auth::id()) }}" class="btn btn-danger mt-2" onclick="confirm('Are You Sure?\n If Yes click OK or Cancel.');">Close Account <i class='bx bx-user-x' style="vertical-align: middle;"></i></a>
                                        <div class="mb-3"><small class="text-danger ">You won't be able to login once account is closed</small></div>
                                    </div>
                                 </div>
                             </div>
                         </div>
                     </div>
                </div>
             </div>
        </div>
    </div>
</section>
@endsection

resources/views/users/applied.blade.php
@extends('layouts.master')
@section('title', 'Jobs Applications')
@section('content')
@include('inc.breadcrumb')
<div class="manage-applications section">
    <div class="container">
        <div class="alerts-inner">
            <div class="row">
                @include('inc.dashboard.sidebar')
                <div class="col-lg-8 col-12">
                    <div class="job-items">
                        @forelse ($applied as $app)
                        <div class="manage-content">
                            <div class="row align-items-center justify-content-center">
                                <div class="col-lg-4 col-md-4">
                                    <div class="title-img">
                                        <h3>
                                            {{ $app->job->title }} <span>{{ $app->job->category->cat_name }}</span>
                                        </h3>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-md-3">
                                    <p><span class="time">{{ $app->job->type->type_name }}</span></p>
                                </div>
                                <div class="col-lg-3 col-md-3">
                                    <p>

                                        @if($app->status == '1')
                                            Pending
                                        @elseif($app->status == '2')
                                            Approved
                                        @else
                                            Rejected
                                        @endif
                                    </p>
                                </div>
                                @if($app->user_id ==  auth()->id())
                                <div class="col-lg-2 col-md-2">
                                        <a href="#" onclick=" event.preventDefault(); document.querySelector('#delete{{$app->id}}').click();">
                                            <i class="lni lni-trash"></i>
                                        </a>
                                </div>
                                @endif
                            </div>
                            <a href="{{ route('dashboard.jobs.applied.delete', $app->id) }}" id="delete{{$app->id}}"></a>
                        </div>
                        @empty
                            <div class="manage-content">
                                <div class="row align-items-center justify-content-center">
                                    <div class="col-lg-12">
                                        <div class="title-img">
                                            <h3>Oops!! You have no job applications at this time.</h3>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforelse
                    </div>

                    <div class="pagination left pagination-md-center">
                        <ul class="pagination-list">
                            {!! $applied->links() !!}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/cpassword.blade.php
@extends('layouts.master')
@section('title', 'Change Password')
@section('content')
    @include('inc.breadcrumb')
    <div class="change-password section">
        <div class="container">
            <div class="alerts-inner">
                <div class="row">
                    @include('inc.dashboard.sidebar')

                    <div class="col-lg-8">
                        <div class="password-content">
                            <h3>Change Password</h3>
                            <p>Here you can change your password please fill up the form.</p>
                            <form method="POST" action="{{ route('dashboard.password.change') }}">
                            @csrf
                            <!-- Table-->
                                @include('inc.dashboard.alert')
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label>Old Password</label>
                                            <input class="form-control" type="password">
                                        </div>

                                        @error('current_password')
                                        <span class="invalid-feedback" role="alert">
                                                    <b>{{ $message }}</b>
                                                </span>
                                        @enderror
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label>New Password</label>
                                            <input class="form-control" type="password"  name="new_password"/>
                                            <i class="bx bxs-low-vision"></i>
                                        </div>

                                        @error('new_password')
                                        <span class="invalid-feedback" role="alert">
                                                    <b>{{ $message }}</b>
                                                </span>
                                        @enderror
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="form-group last">
                                            <label>Confirm Password</label>
                                            <input class="form-control" type="password" name="new_confirm_password"/>
                                            <i class="bx bxs-low-vision"></i>
                                        </div>

                                        @error('new_confirm_password')
                                        <span class="invalid-feedback" role="alert" >
                                                    <b>{{ $message }}</b>
                                                </span>
                                        @enderror
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="button">
                                            <button type="submit" class="btn">Save Change</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/modal.blade.php
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">

resources/views/users/myjobs.blade.php
@extends('layouts.master')
@section('title', 'My Jobs')
@section('content')
@include('inc.dash-bread')
<section>
    <div class="block no-padding">
        <div class="container">
             <div class="row no-gape">
                 @include('inc.sidebar')
                 <div class="col-lg-9 column">
                     <div class="padding-left">
                         <div class="manage-jobs-sec">
                             <h3>@yield('title')</h3>
                             <table>
                                 @if (count($jobs) > 0)

                                 <thead>
                                     <tr>
                                         <td>Job Title</td>
                                         <td>Status</td>
                                         <td>Date</td>
                                         <td></td>
                                     </tr>
                                 </thead>
                                 @endif
                                 <tbody>
                                     @forelse ($jobs as $job)
                                     <tr>
                                         <td>
                                             <div class="table-list-title">
                                                 <i>{{ $job->job->title }} / {{ $job->job->category->cat_name }}</i><br>
                                                 <span><i class="la la-map-marker"></i>{{ $job->job->location }}</span>
                                             </div>
                                         </td>
                                         <td>
                                             <div class="table-list-title">
                                                @if ($job->status == '1')
                                                    <span class="text-warning bold" style="font-weight: bold;">Pending Approval</span>
                                                @elseif ($job->status == '2')
                                                    <span class="text-success bold" style="font-weight: bold;">Approved</span>
                                                @else
                                                    <span class="text-danger bold" style="font-weight: bold;">Rejected</span>
                                                @endif
                                             </div>
                                         </td>
                                         <td>
                                             <span>{{ $job->created_at->format('M d, Y') }}</span><br>
                                         </td>
                                         <td>
                                             <ul class="action_job">
                                                 <li><span>Terminate Job</span><a onclick="confirm('Are You Sure You want to terminate employment?\n If Yes click OK or Cancel.');" href="{{ route('dashboard.jobs.assigned.delete', $job->id) }}" title=""><i class="la la-trash-o"></i></a></li>
                                             </ul>
                                         </td>
                                     </tr>
                                     @empty
                                    <div class="alert alert-warning block d-flex justify-content-between">
                                        <h3>Oops!! You currently have no job assigned to you.</h3>
                                        <a href="{{ route('jobs.home') }}" class="btn btn-success"> Find Jobs <i class="bx bx-right-arrow-alt" style="vertical-align: middle;"></i></a>
                                    </div>
                                     @endforelse
                                 </tbody>
                             </table>
                         </div>
                     </div>
                </div>
             </div>
        </div>
    </div>
</section>
@endsection