routes/web.php
<?php

use App\Models\Job;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $jobs = Job::active()->orderBy('updated_at','DESC');
    return view('pages.index', compact('jobs'));
})->name('home');

Route::get('/about', function () {
    return view('pages.about');
})->name('about');

Route::get('/contact', function () {
    return view('pages.contact');
})->name('contact');

Route::post('contact-send','App\Http\Controllers\ContactController@sendMail')->name('contact.send');


Auth::routes();

Route::prefix('jobs')->name('jobs.')->group( function () {
    Route::get('/','App\Http\Controllers\JobController@index')->name('home');
    Route::get('/{job}','App\Http\Controllers\JobController@show')->name('show');
    Route::post('/','App\Http\Controllers\JobController@searchJobs')->name('search');
    Route::get('/applied','App\Http\Controllers\JobController@applied')->name('applied');
});

Route::get('/home','App\Http\Controllers\HomeController@index');
Route::prefix('dashboard')->middleware('auth')->name('dashboard.')->group(function(){
    Route::get('/profile/{user}','App\Http\Controllers\AdminController@userProfile')->name('profile.user');
    Route::get('/profile','App\Http\Controllers\AccountController@index')->name('profile.user');
    Route::patch('/profile/update/{user}','App\Http\Controllers\AccountController@profileUpdate')->name('profile.update');
    Route::get('/become/employee','App\Http\Controllers\EmployeeController@create')->name('become.employee');
    Route::post('/become/employee','App\Http\Controllers\EmployeeController@store')->name('become.employee');
    Route::get('/change-password','App\Http\Controllers\AdminController@cPassword')->name('change.password');
    Route::get('/deactivate/{user}','App\Http\Controllers\AccountController@deactivate')->name('deactivate.account');
    //User Leaves Route
    Route::get('/leaves','App\Http\Controllers\LeaveController@index')->name('leaves.applied');
    Route::get('/leave/delete/{leave}','App\Http\Controllers\LeaveController@destroy')->name('leave.delete');
    Route::post('/leave/apply','App\Http\Controllers\LeaveController@store')->name('leave.apply');

    Route::post('/password/change','App\Http\Controllers\AdminController@changePassword')->name('password.change');
    Route::get('/','App\Http\Controllers\AdminController@index')->name('home');

        Route::get('/jobs/applied','App\Http\Controllers\JobController@applied')->name('jobs.applied');
        Route::get('/jobs','App\Http\Controllers\JobAssignedController@index')->name('jobs.assigned');
        Route::get('/jobs/assigned/delete/{jobAssigned}','App\Http\Controllers\JobAssignedController@destroy')->name('jobs.assigned.delete');
        Route::get('/jobs/applied/delete/{jobApplication}','App\Http\Controllers\JobController@jobAppDestroy')->name('jobs.applied.delete');
        Route::post('/jobs/apply/{job}','App\Http\Controllers\JobController@jobApply')->name('jobs.apply');
        Route::get('/account/settings','App\Http\Controllers\AccountController@settings')->name('account.settings');
        Route::post('/bank/store','App\Http\Controllers\AccountController@bankDetails')->name('bank.store');
        Route::post('/document/store','App\Http\Controllers\AccountController@documentUpload')->name('document.store');

    Route::prefix('admin')->name('admin.')->middleware('can:admin')->group(function(){
        Route::get('/','App\Http\Controllers\AdminController@adminHome')->name('home');

        // Admin Leave Routes
        Route::get('/leaves','App\Http\Controllers\LeaveController@adminLeaves')->name('leaves');
        Route::get('/leave/reject/{leave}','App\Http\Controllers\LeaveController@rejectLeave')->name('leave.reject');
        Route::get('/leave/accept/{leave}','App\Http\Controllers\LeaveController@acceptLeave')->name('leave.accept');

        Route::get('/company','App\Http\Controllers\CompanyController@index')->name('company');
        Route::post('/company/save','App\Http\Controllers\CompanyController@store')->name('company.save');
        Route::post('/company/logo/upload','App\Http\Controllers\CompanyController@uploadImage')->name('company.logo.upload');
        Route::prefix('employees')->name('employees.')->group(function(){
            Route::get('/','App\Http\Controllers\AdminController@employees')->name('home');
            Route::get('/delete/{employee}','App\Http\Controllers\AdminController@employeeDestroy')->name('delete');
            Route::get('/{employee}','App\Http\Controllers\AdminController@employee')->name('show');
        });
        Route::prefix('users')->name('users.')->group(function(){
            Route::get('/','App\Http\Controllers\AdminController@users')->name('home');
            Route::post('/store','App\Http\Controllers\AdminController@userSave')->name('store');
            Route::get('/add','App\Http\Controllers\AdminController@userAdd')->name('add');
            Route::patch('/update/{user}','App\Http\Controllers\AdminController@userUpdate')->name('update');
            Route::get('/edit/{user}','App\Http\Controllers\AdminController@userAdd')->name('edit');
            Route::get('/delete/{user}','App\Http\Controllers\AdminController@userDestroy')->name('delete');
            Route::get('/activate/{user}','App\Http\Controllers\AdminController@userActivate')->name('activate');
            Route::get('/deactivate/{user}','App\Http\Controllers\AdminController@userDeactivate')->name('deactivate');
        });
        Route::prefix('category')->name('category.')->group(function(){
            Route::get('/','App\Http\Controllers\AdminController@category')->name('home');
            Route::post('/store','App\Http\Controllers\AdminController@categorySave')->name('store');
            Route::get('/add','App\Http\Controllers\AdminController@categoryAdd')->name('add');
            Route::patch('/update/{jobCategory}','App\Http\Controllers\AdminController@categoryUpdate')->name('update');
            Route::get('/edit/{jobCategory}','App\Http\Controllers\AdminController@categoryAdd')->name('edit');
            Route::get('/delete/{jobCategory}','App\Http\Controllers\AdminController@categoryDestroy')->name('delete');
        });
        Route::prefix('jobs')->name('jobs.')->group(function(){
            Route::get('/','App\Http\Controllers\AdminController@jobs')->name('home');
            Route::get('/add','App\Http\Controllers\AdminController@jobAdd')->name('add');
            Route::post('/store','App\Http\Controllers\AdminController@jobSave')->name('store');
            Route::patch('/update/{job}','App\Http\Controllers\AdminController@jobUpdate')->name('update');
            Route::get('/edit/{job}','App\Http\Controllers\AdminController@jobAdd')->name('edit');
            Route::get('/delete/{job}','App\Http\Controllers\AdminController@jobDestroy')->name('delete');
            Route::get('/applications','App\Http\Controllers\AdminController@applications')->name('applications');
            Route::get('/{job}/applications','App\Http\Controllers\AdminController@jobApplications')->name('applications.specific');
            Route::get('/applications/delete/{jobApplication}','App\Http\Controllers\AdminController@jobAppDestroy')->name('applications.delete');
            Route::get('/applications/accept/{jobApplication}','App\Http\Controllers\AdminController@jobAppAccept')->name('applications.accept');
            Route::get('/applications/reject/{jobApplication}','App\Http\Controllers\AdminController@jobAppReject')->name('applications.reject');
            Route::get('/candidates','App\Http\Controllers\AdminController@jobCandidates')->name('candidates');
        });
    });
});

Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/inc/breadcrumb.blade.php
<div class="breadcrumbs overlay">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="breadcrumbs-content">
                    <h1 class="page-title">@yield('title')</h1>
                    <p>
                    </p>
                </div>
                <ul class="breadcrumb-nav">
                    <li><a href="{{ route('home') }}">Home</a></li>
                    <li>@yield('title')</li>
                </ul>
            </div>
        </div>
    </div>
</div>

resources/views/inc/footer.blade.php
<footer class="footer">
    <div class="footer-middle">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6 col-12">
                    <div class="f-about single-footer">
                        <div class="logo">
                            <a href="{{ route('home') }}"><img style="height: 55px; width: auto;" src="{{ asset('assets/images/logo/logo2.png') }}" alt="{{ $appName }}" /></a>
                        </div>
                        <p>

                        </p>
                        <ul class="contact-address">
                            <li><span>Address:</span> {{ $appAddress }}</li>
                            <li>
                                <span>Email:</span>
                                <a href="mailto:{{ $appEmail }}">{{ $appEmail }}</a>
                            </li>
                            <li><span>Call:</span><a href="tel:{{ $appTel }}">{{ $appTel }}</a></li>
                        </ul>
                        <div class="footer-social">
                            <ul>
                                <li>
                                    <a href="#"><i class="lni lni-facebook-original"></i></a>
                                </li>
                                <li>
                                    <a href="#"><i class="lni lni-twitter-original"></i></a>
                                </li>
                                <li>
                                    <a href="#"><i class="lni lni-linkedin-original"></i></a>
                                </li>
                                <li>
                                    <a href="#"><i class="lni lni-pinterest"></i></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-8 col-12">
                    <div class="row">
                        <div class="col-lg-5 col-md-6 col-12">
                            <div class="single-footer f-link">
                                <h3>Sitemap</h3>
                                <ul>
                                    <li><a href="{{ route('jobs.home') }}">Job Openings</a></li>
                                    <li><a href="#">My Resume</a></li>
                                    <li><a href="{{ route('about') }}">About Us</a></li>
                                    <li><a href="{{ route('contact') }}">Contact</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-7 col-md-6 col-12">
                            <div class="single-footer newsletter">
                                <h3>Join Our Newsletter</h3>
                                <p>
                                    Subscribe to get the latest jobs posted, candidates...
                                </p>
                                <form action="#" method="POST" class="newsletter-inner">
                                    <input  placeholder="Your email address" class="common-input"
                                            onfocus="this.placeholder = ''" onblur="this.placeholder = 'Your email address'" required=""
                                            type="email" />
                                    <div class="button">
                                        <button class="btn">
                                            Subscribe Now! <span class="dir-part"></span>
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="footer-bottom">
        <div class="container">
            <div class="inner">
                <div class="row">
                    <div class="col-12">
                        <div class="left">
                            <p>
                                Designed and Developed by <a href="{{ $appCl }}" target="_blank">{{ $appCr }}</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

resources/views/inc/navbar.blade.php
<header class="header @if(\Route::currentRouteName() != 'home') other-page @endif">
    <div class="navbar-area">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12">
                    <nav class="navbar navbar-expand-lg">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="toggler-icon"></span>
                            <span class="toggler-icon"></span>
                            <span class="toggler-icon"></span>
                        </button>
                        <a class="navbar-brand logo" href="{{ route('home') }}">
                            <img class="logo1" style="height: 40px; width: auto;" src="{{ asset('assets/images/logo/logo2.png') }}" alt="{{ $appName }}" />
                        </a>
                        <div class="collapse navbar-collapse sub-menu-bar" id="navbarSupportedContent">
                            <ul id="nav" class="navbar-nav ml-auto">
                                <li class="nav-item">
                                    <a @if(\Route::currentRouteName() == 'home')  class="active" @endif href="{{ route('home') }}">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a @if(\Route::is('jobs*'))  class="active" @endif href="{{ route('jobs.home') }}">Job Board</a>
                                </li>
                                <li class="nav-item">
                                    <a @if(\Route::currentRouteName() == 'about')  class="active" @endif href="{{ route('about') }}">About Us</a>
                                </li>
                                <li class="nav-item">
                                    <a @if(\Route::currentRouteName() == 'contact')  class="active" @endif href="{{ route('contact') }}">Contact Us</a>
                                </li>
                            </ul>
                        </div>
                        @auth()
                        <div class="button">
                            <a href="{{ route('logout') }}" onclick="event.preventDefault();
                                 document.getElementById('logout-form2').submit();" class="login"><i
                                    class="lni lni-upload"></i> Logout</a>
                            @can('admin')
                            <a href="{{ route('dashboard.admin.jobs.add') }}" class="btn">Post Job</a>
                            @else
                            <a href="{{ route('dashboard.profile.user') }}" class="btn">My Profile</a>
                            @endif
                            <form id="logout-form2" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </div>
                        @else
                        <div class="button">
                            <a href="{{ route('login') }}" class="login"><i
                                    class="lni lni-lock-alt"></i> Login</a>
                            <a href="{{ route('register') }}" class="btn">Sign Up</a>
                        </div>
                        @endauth
                    </nav>
                </div>
            </div>
        </div>
    </div>
</header>

resources/views/inc/scripts.blade.php
<script src="{{ asset('assets/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/js/wow.min.js') }}"></script>
<script src="{{ asset('assets/js/tiny-slider.js') }}"></script>
<script src="{{ asset('assets/js/glightbox.min.js') }}"></script>
<script src="{{ asset('assets/js/main.js') }}"></script>
<script type="text/javascript">
    //====== Clients Logo Slider
    tns({
        container: ".client-logo-carousel",
        slideBy: "page",
        autoplay: true,
        autoplayButtonOutput: false,
        mouseDrag: true,
        gutter: 15,
        nav: false,
        controls: false,
        responsive: {
            0: {
                items: 1,
            },
            540: {
                items: 2,
            },
            768: {
                items: 3,
            },
            992: {
                items: 4,
            },
            1170: {
                items: 6,
            },
        },
    });
    //========= testimonial
    tns({
        container: ".testimonial-slider",
        items: 1,
        slideBy: "page",
        autoplay: false,
        mouseDrag: true,
        gutter: 0,
        nav: false,
        controls: true,
        controlsText: [
            '<i class="lni lni-arrow-left"></i>',
            '<i class="lni lni-arrow-right"></i>',
        ],
        responsive: {
            0: {
                items: 1,
            },
            540: {
                items: 1,
            },
            768: {
                items: 1,
            },
            992: {
                items: 1,
            },
            1170: {
                items: 1,
            },
        },
    });

    //========= glightbox
    GLightbox({
        href: "assets/images/video/video.mp4",
        type: "video",
        source: "youtube", //vimeo, youtube or local
        width: 900,
        autoplayVideos: true,
    });
</script>
<!-- Scripts
================================================== -->

resources/views/inc/styles.blade.php
<link rel="stylesheet" href="{{ asset('assets/css/fonts.css') }}">

<link rel="stylesheet" href="{{ asset('assets/css/bootstrap.min.css') }}" />
<link rel="stylesheet" href="{{ asset('assets/css/LineIcons.2.0.css') }}" />
<link rel="stylesheet" href="{{ asset('assets/css/animate.css') }}" />
<link rel="stylesheet" href="{{ asset('assets/css/tiny-slider.css') }}" />
<link rel="stylesheet" href="{{ asset('assets/css/glightbox.min.css') }}" />
<link rel="stylesheet" href="{{ asset('assets/css/main.css') }}" />
<meta name="viewport" content="width=device-width,height=device-height,initial-scale=1.0">