routes/web.php
<?php

use App\Models\Job;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $jobs = Job::active()->orderBy('updated_at','DESC');
    return view('pages.index', compact('jobs'));
})->name('home');

Route::get('/about', function () {
    return view('pages.about');
})->name('about');

Route::get('/contact', function () {
    return view('pages.contact');
})->name('contact');

Route::post('contact-send','App\Http\Controllers\ContactController@sendMail')->name('contact.send');


Auth::routes();

Route::prefix('jobs')->name('jobs.')->group( function () {
    Route::get('/','App\Http\Controllers\JobController@index')->name('home');
    Route::get('/{job}','App\Http\Controllers\JobController@show')->name('show');
    Route::post('/','App\Http\Controllers\JobController@searchJobs')->name('search');
    Route::get('/applied','App\Http\Controllers\JobController@applied')->name('applied');
});

Route::get('/home','App\Http\Controllers\HomeController@index');
Route::prefix('dashboard')->middleware('auth')->name('dashboard.')->group(function(){
    Route::get('/profile/{user}','App\Http\Controllers\AdminController@userProfile')->name('profile.user');
    Route::get('/profile','App\Http\Controllers\AccountController@index')->name('profile.user');
    Route::patch('/profile/update/{user}','App\Http\Controllers\AccountController@profileUpdate')->name('profile.update');
    Route::get('/become/employee','App\Http\Controllers\EmployeeController@create')->name('become.employee');
    Route::post('/become/employee','App\Http\Controllers\EmployeeController@store')->name('become.employee');
    Route::get('/change-password','App\Http\Controllers\AdminController@cPassword')->name('change.password');
    Route::get('/deactivate/{user}','App\Http\Controllers\AccountController@deactivate')->name('deactivate.account');
    //User Leaves Route
    Route::get('/leaves','App\Http\Controllers\LeaveController@index')->name('leaves.applied');
    Route::get('/leave/delete/{leave}','App\Http\Controllers\LeaveController@destroy')->name('leave.delete');
    Route::post('/leave/apply','App\Http\Controllers\LeaveController@store')->name('leave.apply');

    Route::post('/password/change','App\Http\Controllers\AdminController@changePassword')->name('password.change');
    Route::get('/','App\Http\Controllers\AdminController@index')->name('home');

        Route::get('/jobs/applied','App\Http\Controllers\JobController@applied')->name('jobs.applied');
        Route::get('/jobs','App\Http\Controllers\JobAssignedController@index')->name('jobs.assigned');
        Route::get('/jobs/assigned/delete/{jobAssigned}','App\Http\Controllers\JobAssignedController@destroy')->name('jobs.assigned.delete');
        Route::get('/jobs/applied/delete/{jobApplication}','App\Http\Controllers\JobController@jobAppDestroy')->name('jobs.applied.delete');
        Route::post('/jobs/apply/{job}','App\Http\Controllers\JobController@jobApply')->name('jobs.apply');
        Route::get('/account/settings','App\Http\Controllers\AccountController@settings')->name('account.settings');
        Route::post('/bank/store','App\Http\Controllers\AccountController@bankDetails')->name('bank.store');
        Route::post('/document/store','App\Http\Controllers\AccountController@documentUpload')->name('document.store');

    Route::prefix('admin')->name('admin.')->middleware('can:admin')->group(function(){
        Route::get('/','App\Http\Controllers\AdminController@adminHome')->name('home');

        // Admin Leave Routes
        Route::get('/leaves','App\Http\Controllers\LeaveController@adminLeaves')->name('leaves');
        Route::get('/leave/reject/{leave}','App\Http\Controllers\LeaveController@rejectLeave')->name('leave.reject');
        Route::get('/leave/accept/{leave}','App\Http\Controllers\LeaveController@acceptLeave')->name('leave.accept');

        Route::get('/company','App\Http\Controllers\CompanyController@index')->name('company');
        Route::post('/company/save','App\Http\Controllers\CompanyController@store')->name('company.save');
        Route::post('/company/logo/upload','App\Http\Controllers\CompanyController@uploadImage')->name('company.logo.upload');
        Route::prefix('employees')->name('employees.')->group(function(){
            Route::get('/','App\Http\Controllers\AdminController@employees')->name('home');
            Route::get('/delete/{employee}','App\Http\Controllers\AdminController@employeeDestroy')->name('delete');
            Route::get('/{employee}','App\Http\Controllers\AdminController@employee')->name('show');
        });
        Route::prefix('users')->name('users.')->group(function(){
            Route::get('/','App\Http\Controllers\AdminController@users')->name('home');
            Route::post('/store','App\Http\Controllers\AdminController@userSave')->name('store');
            Route::get('/add','App\Http\Controllers\AdminController@userAdd')->name('add');
            Route::patch('/update/{user}','App\Http\Controllers\AdminController@userUpdate')->name('update');
            Route::get('/edit/{user}','App\Http\Controllers\AdminController@userAdd')->name('edit');
            Route::get('/delete/{user}','App\Http\Controllers\AdminController@userDestroy')->name('delete');
            Route::get('/activate/{user}','App\Http\Controllers\AdminController@userActivate')->name('activate');
            Route::get('/deactivate/{user}','App\Http\Controllers\AdminController@userDeactivate')->name('deactivate');
        });
        Route::prefix('category')->name('category.')->group(function(){
            Route::get('/','App\Http\Controllers\AdminController@category')->name('home');
            Route::post('/store','App\Http\Controllers\AdminController@categorySave')->name('store');
            Route::get('/add','App\Http\Controllers\AdminController@categoryAdd')->name('add');
            Route::patch('/update/{jobCategory}','App\Http\Controllers\AdminController@categoryUpdate')->name('update');
            Route::get('/edit/{jobCategory}','App\Http\Controllers\AdminController@categoryAdd')->name('edit');
            Route::get('/delete/{jobCategory}','App\Http\Controllers\AdminController@categoryDestroy')->name('delete');
        });
        Route::prefix('jobs')->name('jobs.')->group(function(){
            Route::get('/','App\Http\Controllers\AdminController@jobs')->name('home');
            Route::get('/add','App\Http\Controllers\AdminController@jobAdd')->name('add');
            Route::post('/store','App\Http\Controllers\AdminController@jobSave')->name('store');
            Route::patch('/update/{job}','App\Http\Controllers\AdminController@jobUpdate')->name('update');
            Route::get('/edit/{job}','App\Http\Controllers\AdminController@jobAdd')->name('edit');
            Route::get('/delete/{job}','App\Http\Controllers\AdminController@jobDestroy')->name('delete');
            Route::get('/applications','App\Http\Controllers\AdminController@applications')->name('applications');
            Route::get('/{job}/applications','App\Http\Controllers\AdminController@jobApplications')->name('applications.specific');
            Route::get('/applications/delete/{jobApplication}','App\Http\Controllers\AdminController@jobAppDestroy')->name('applications.delete');
            Route::get('/applications/accept/{jobApplication}','App\Http\Controllers\AdminController@jobAppAccept')->name('applications.accept');
            Route::get('/applications/reject/{jobApplication}','App\Http\Controllers\AdminController@jobAppReject')->name('applications.reject');
            Route::get('/candidates','App\Http\Controllers\AdminController@jobCandidates')->name('candidates');
        });
    });
});

Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/JobType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class JobType extends Model
{
    use HasFactory;

    protected $primaryKey = 'type_id';

    protected $fillable = ['type_name', 'status'];

    public function scopeActive($scope)
    {
        return $scope->whereStatus('1');
    }

    public function jobs()
    {
        return $this->hasMany(Job::class, 'type_id');
    }
}

app/Http/Controllers/JobController.php
<?php

namespace App\Http\Controllers;

use App\Models\Job;
use App\Models\JobApplication;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Session;

class JobController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $now = \Carbon\Carbon::now()->format('Y-m-d');
        // $jobs = Job::whereStatus('1')->where('close_date', '>', $now)->orderBy('updated_at', 'DESC')->simplePaginate(6);
        $jobs = Job::active()->orderBy('updated_at', 'DESC')->paginate(20);
        return view('jobs.index', compact('jobs'));
    }


    public function applied()
    {
        $applied = JobApplication::orderBy('updated_at', 'DESC')->whereUser_id(\Auth::id())->paginate(20);
        return view('users.applied', compact('applied'));
    }

    public function jobAppDestroy(Request $request, JobApplication $jobApplication)
    {

        if(\Auth::user()->isOwner($jobApplication->user_id)){
            if(\File::exists(public_path($jobApplication->resume))){
                \File::delete(public_path($jobApplication->resume));
            }
            $destroy = $jobApplication->delete();
            if($destroy){
                if($request->ajax()){
                    return response()->json(['msg' => 'Job Application Deleted Successfully!!'], 200);
                }
                Session::flash('success', "Job Application Deleted Successfully!!");
                return Redirect::back();
            }else{
                if($request->ajax()){
                    return response()->json(['msg' => 'Oops!! Job Application Failed To Delete.'], 422);
                }
                Session::flash('error', "Oops!! Job Application Failed To Delete.");
                return Redirect::back();
            }
        }else{
            if($request->ajax()){
                return response()->json(['msg' => 'Oops!! Unauthorized Delete Action.'], 422);
            }
            Session::flash('error', "Oops!! Unauthorized Delete Action.");
            return Redirect::back();
        }
    }


    public function searchJobs(Request $request)
    {
        $now = \Carbon\Carbon::now()->format('Y-m-d');
        if ($request->filter)
        {
            $jobs = Job::available()->where('title', 'LIKE', "%{$request->filter}%")->orWhereHas('category', function($q) use($request){
                $q->where('cat_name', 'LIKE', "%{$request->filter}%");
            })->paginate(15);
            $query = $request->filter;
            return view('jobs.index', compact('jobs', 'query'));
        }
        elseif($request->search){
            $jobs = Job::available()
                ->when(!empty($request->get('cat_id')) , function ($query) use($request){
                    return $query->where('cat_id', $request->cat_id);
                })
                ->when(!empty($request->get('type_id')) , function ($query) use($request){
                    return $query->where('type_id', $request->type_id);
                })
                ->when (!empty($request->input('search')) , function ($query) use($request){
                    return $query->where('title', 'LIKE', "%{$request->search}%");
                })
                ->when (!empty($request->input('location')) , function ($query) use($request){
                    return $query->where('location', 'LIKE', "%{$request->location}%");
                })
                ->when (!empty($request->rate) , function ($query) use($request){
                    if ($request->rate == '200')
                    {
                        return $query->where('wages', '>=', 200);
                    }
                    else
                    {
                        return $query->whereBetween('wages', $request->rate);
                    }
                })
                ->when(!empty($request->get('sort')) , function ($query) use($request){
                   if ($request->sort == 'oldest'){
                       return $query->orderBy("created_at", "asc");
                   }elseif ($request->sort == 'ratehigh'){
                       return $query->orderBy("wages", "desc");
                   }elseif ($request->sort == 'ratelow'){
                        return $query->orderBy("wages", "asc");
                    }else{
                        return $query->orderBy("created_at", "desc");
                    }
                })->paginate(15);
            $query = $request->search;
            return view('jobs.index', compact('jobs', 'query'));
        }else{
            Session::flash('error', "Oops!! Search box is empty.");
            return Redirect::back();
        }
    }

    public function searchCatJobs(Request $request)
    {
        if ($request->filter)
        {
            $jobs = Job::available()->where('title', 'LIKE', "%{$request->filter}%")->orWhereHas('category', function($q) use($request){
                $q->where('cat_name', 'LIKE', "%{$request->filter}%");
            })->paginate(15);
            return view('jobs.index', compact('jobs', 'query'));
        }
        else
        {
            return Redirect::route('jobs.homr');
        }
    }


    public function jobApply(Job $job, Request $request)
    {
        // dd($job);
        if (JobApplication::where('user_id', \Auth::id())->where('job_id', $job->id)->first()) {
            if($request->ajax()){
                return response()->json(['msg' => 'Oops!! You Already Applied For This Job.'], 422);
            }
            Session::flash('error', "Oops!! You Already Applied For This Job.");
            return Redirect::back();
        }else{
            $apply = new JobApplication();
            $apply->user_id = \Auth::id();
            $apply->job_id = $job->id;
            $apply->company_id = 1;
            $apply->status = '1';
            $apply->cover_letter = $request->cover_letter;
            if ($request->hasfile('resume')) {
                $file = $request->file('resume');
                $filename = \Str::slug(\Auth::user()->name()).'-resume-'.time().'.'.$file->extension();
                $file->move(public_path().'/uploads/employee_documents/resume/', $filename);
                $apply->resume = '/uploads/employee_documents/resume/'.$filename;
            }
            if ($apply->save()) {
                if($request->ajax()){
                    return response()->json(['msg' => 'Job Application Successfully!!'], 200);
                }
                Session::flash('success', "Job Application Successfully!!");
                return Redirect::back();
            } else {
                if($request->ajax()){
                    return response()->json(['msg' => 'Oops!! Job Application Failed.'], 422);
                }
                Session::flash('error', "Oops!! Job Application Failed.");
                return Redirect::back();
            }
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Job  $job
     * @return \Illuminate\Http\Response
     */
    public function show(Job $job)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Job  $job
     * @return \Illuminate\Http\Response
     */
    public function edit(Job $job)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Job  $job
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Job $job)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Job  $job
     * @return \Illuminate\Http\Response
     */
    public function destroy(Job $job)
    {
        //
    }
}

resources/views/admin/jobs/categories.blade.php
@extends('layouts.master')
@section('title', 'Manage Categories')
@section('content')
    @include('inc.breadcrumb')
    <div class="manage-jobs section">
        <div class="container">
            <div class="alerts-inner">
                <div class="row">
                    @include('inc.dashboard.sidebar')
                    <div class="col-lg-8 col-12">
                        @include('inc.dashboard.alert')
                        <div class="job-items">
                            @if(count($cats) > 0)
                                <div class="manage-list">
                                    <div class="row">
                                        <div class="col-lg-3 col-md-3 col-12">
                                            <p>Category Name</p>
                                        </div>
                                        <div class="col-lg-3 col-md-3 col-12">
                                            <p>Date Created</p>
                                        </div>
                                        <div class="col-lg-3 col-md-3 col-12">
                                            <p>Status</p>
                                        </div>
                                        <div class="col-lg-3 col-md-3 col-12">
                                            <p>Actions</p>
                                        </div>
                                    </div>
                                </div>
                            @endif
                            @forelse($cats as $cat)
                                <div class="manage-content">
                                    <div class="row align-items-center justify-content-center">
                                        <div class="col-lg-3 col-md-3 col-12">
                                            <h3>{{ $cat->cat_name }}</h3>
                                        </div>
                                        <div class="col-lg-3 col-md-3 col-12">
                                            <p>
                                                {{ $cat->created_at->format('dS M, Y') }}
                                            </p>
                                        </div>
                                        <div class="col-lg-3 col-md-3 col-12">
                                            <p>
                                                @if($cat->status == '1')
                                                    Active
                                                @else
                                                    Inactive
                                                @endif
                                            </p>
                                        </div>
                                        <div class="col-lg-3 col-md-3 col-12">
                                            <p>
                                                <a href="{{ route('dashboard.admin.category.edit', $cat->cat_id) }}" class="mx-2"><i class="lni lni-pencil"></i> Edit</a>
                                                <a href="{{ route('dashboard.admin.category.delete', $cat->cat_id) }}" onclick="return confirm('Are you sure you want to delete this category?');" class="delete mx-2"><i class="lni lni-trash"></i> Delete</a>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            @empty
                                <div class="manage-content">
                                    <div class="row align-items-center justify-content-center">
                                        <div class="col-lg-12 col-12">
                                            <h4>Oops!! No Job Categories Found.</h4>
                                        </div>
                                    </div>
                                </div>
                            @endforelse
                        </div>

                        <div class="pagination left pagination-md-center">
                            <ul class="pagination-list">
                                {!! $cats->links() !!}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <!-- Dashboard -->
    <div id="dashboard">

        <!-- Navigation
        ================================================== -->
    @include('inc.dashboard.sidebar')
    <!-- Content
	================================================== -->
        <div class="dashboard-content">
            @include('inc.dashboard.breadcrumb')


            <div class="row">

                <!-- Table-->
                <div class="col-lg-12 col-md-12">

                   @include('inc.dashboard.alert')
                    <div class="dashboard-list-box margin-top-30">
                        <div class="dashboard-list-box-content">

                            <!-- Table -->

                            <table class="manage-table responsive-table">
                                @if(count($cats) > 0)
                                <tr>
                                    <th><i class="fa fa-file-text"></i> Category Name</th>
                                    <th><i class="fa fa-calendar"></i> Date Created</th>
                                    <th><i class="fa fa-calendar"></i> Status</th>
                                    <th></th>
                                </tr>
                                @endif
                                @forelse($cats as $cat)
                                <!-- Item #2 -->
                                <tr>
                                    <td class="title"><a href="#">{{ $cat->cat_name }}</a></td>
                                    <td>{{ $cat->created_at->format('dS M, Y') }}</td>
                                    <td class="centered">
                                        @if($cat->status == '1')
                                            Active
                                        @else
                                            Inactive
                                        @endif
                                    </td>
                                    <td class="action">
                                        <a href="{{ route('dashboard.admin.category.edit', $cat->cat_id) }}"><i class="fa fa-pencil"></i> Edit</a>
                                        <a href="#"><i class="fa  fa-check "></i> Assign To</a>
                                        <a href="{{ route('dashboard.admin.category.delete', $cat->cat_id) }}" onclick="return confirm('Are you sure you want to delete this job?');" class="delete"><i class="fa fa-remove"></i> Delete</a>
                                    </td>
                                </tr>
                                @empty

                                <!-- Item #2 -->
                                    <tr>
                                        <td class="title"><a href="#">Oops!! No Job Categories Found.</a></td>
                                    </tr>
                                @endforelse


                                    <div class="pagination-container">
                                        <nav class="pagination">
                                            {!! $cats->links() !!}
                                        </nav>

                                        {{--                <nav class="pagination-next-prev">--}}
                                        {{--                    <ul>--}}
                                        {{--                        <li><a href="#" class="prev">Previous</a></li>--}}
                                        {{--                        <li><a  2href="#" class="next">Next</a></li>--}}
                                        {{--                    </ul>--}}
                                        {{--                </nav>--}}
                                    </div>
                            </table>

                        </div>
                    </div>
                    <a href="{{ route('dashboard.admin.category.add') }}" class="button margin-top-30">Add New Category</a>
                </div>

                @include('inc.dashboard.footer')
            </div>

        </div>
        <!-- Content / End -->

    </div>
    <!-- Dashboard / End -->
@endsection

resources/views/admin/jobs/cover-modal.blade.php
<!-- Modal -->
<div class="modal fade" id="applicaionCL{{ $app->id }}" tabindex="2" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">{{ $app->job->title }} Application</h5>
            <button type="button" class="
            circle-32
            btn-reset
            bg-white
            pos-abs-tr
            mt-md-n6
            mr-lg-n6
            focus-reset
            z-index-supper
          " data-dismiss="modal">
                <i class="lni lni-close"></i>
            </button>
        </div>
        <div class="modal-body">
          <div class="row">
              <div class="col-md-12">
                  <h5>Application Cover Letter</h5>
                  {!! $app->cover_letter !!}

              </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" onclick="event.preventDefault(); document.getElementById('apply-form{{ $app->id }}').submit();" class="btn btn-success">Apply Now <i class="bx bx-right-arrow-alt" style="vertical-align: middle;"></i></button>
        </div>
      </div>
    </div>
  </div>

resources/views/admin/jobs/create-category.blade.php
@extends('layouts.master')
@isset($jobCategory->cat_id)
@section('title', \Str::limit($jobCategory->cat_name, 25))
@else
@section('title', 'Add Job category')
@endisset
@section('content')
    @include('inc.breadcrumb')
    <section class="job-post section">
        <div class="container">
            <div class="row">
                @include('inc.dashboard.sidebar')
                <div class="col-lg-8 col-12">
                    <div class="job-information">
                        <h3 class="title">Category Details</h3>
                        @include('inc.dashboard.alert')
                        @isset($jobCategory->cat_id)
                            <form class="col-lg-12 col-md-12" method="POST" action="{{ route('dashboard.admin.category.update', $jobCategory->cat_id) }}">
                                @method('patch')
                        @else
                            <form class="col-lg-12 col-md-12" method="POST" action="{{ route('dashboard.admin.category.store') }}">
                        @endisset
                                        @csrf
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <label>Category Name</label>
                                                    <input class="form-control" type="text"  name="cat_name" placeholder="" value="{{ old('cat_name', $jobCategory->cat_name) }}"/>
                                                </div>


                                                @error('cat_name')
                                                <span class="invalid-feedback" role="alert">
                                                    <b>{{ $message }}</b>
                                                </span>
                                                @enderror
                                            </div>
                                            <div class="col-lg-12 my-3">
                                                <!-- Status -->
                                                <div class="form-check-inline">
                                                    <label>Category Status*</label>
                                                    <label style="display: inline-block !important;" class="mx-3" for="status-publish">
                                                        <input type="radio" value="1" id="status-publish" @if(old('status', $jobCategory->status) == '1') checked @endif name="status">
                                                        Publish
                                                    </label>
                                                    <label style="display: inline-block !important;" class="mx-3" for="status-draft">
                                                        <input type="radio" value="0" id="status-draft" @if(old('status', $jobCategory->status) == '0') checked @endif name="status">
                                                        Draft
                                                    </label>
                                                    @error('status')
                                                    <span class="invalid-feedback" role="alert">
                                                        <b>{{ $message }}</b>
                                                    </span>
                                                    @enderror
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-12 button">
                                                <button type="submit" class="btn">Save Category</button>
                                            </div>
                                        </div>
                                    </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection