routes/web.php
<?php

use App\Models\Job;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $jobs = Job::active()->orderBy('updated_at','DESC');
    return view('pages.index', compact('jobs'));
})->name('home');

Route::get('/about', function () {
    return view('pages.about');
})->name('about');

Route::get('/contact', function () {
    return view('pages.contact');
})->name('contact');

Route::post('contact-send','App\Http\Controllers\ContactController@sendMail')->name('contact.send');


Auth::routes();

Route::prefix('jobs')->name('jobs.')->group( function () {
    Route::get('/','App\Http\Controllers\JobController@index')->name('home');
    Route::get('/{job}','App\Http\Controllers\JobController@show')->name('show');
    Route::post('/','App\Http\Controllers\JobController@searchJobs')->name('search');
    Route::get('/applied','App\Http\Controllers\JobController@applied')->name('applied');
});

Route::get('/home','App\Http\Controllers\HomeController@index');
Route::prefix('dashboard')->middleware('auth')->name('dashboard.')->group(function(){
    Route::get('/profile/{user}','App\Http\Controllers\AdminController@userProfile')->name('profile.user');
    Route::get('/profile','App\Http\Controllers\AccountController@index')->name('profile.user');
    Route::patch('/profile/update/{user}','App\Http\Controllers\AccountController@profileUpdate')->name('profile.update');
    Route::get('/become/employee','App\Http\Controllers\EmployeeController@create')->name('become.employee');
    Route::post('/become/employee','App\Http\Controllers\EmployeeController@store')->name('become.employee');
    Route::get('/change-password','App\Http\Controllers\AdminController@cPassword')->name('change.password');
    Route::get('/deactivate/{user}','App\Http\Controllers\AccountController@deactivate')->name('deactivate.account');
    //User Leaves Route
    Route::get('/leaves','App\Http\Controllers\LeaveController@index')->name('leaves.applied');
    Route::get('/leave/delete/{leave}','App\Http\Controllers\LeaveController@destroy')->name('leave.delete');
    Route::post('/leave/apply','App\Http\Controllers\LeaveController@store')->name('leave.apply');

    Route::post('/password/change','App\Http\Controllers\AdminController@changePassword')->name('password.change');
    Route::get('/','App\Http\Controllers\AdminController@index')->name('home');

        Route::get('/jobs/applied','App\Http\Controllers\JobController@applied')->name('jobs.applied');
        Route::get('/jobs','App\Http\Controllers\JobAssignedController@index')->name('jobs.assigned');
        Route::get('/jobs/assigned/delete/{jobAssigned}','App\Http\Controllers\JobAssignedController@destroy')->name('jobs.assigned.delete');
        Route::get('/jobs/applied/delete/{jobApplication}','App\Http\Controllers\JobController@jobAppDestroy')->name('jobs.applied.delete');
        Route::post('/jobs/apply/{job}','App\Http\Controllers\JobController@jobApply')->name('jobs.apply');
        Route::get('/account/settings','App\Http\Controllers\AccountController@settings')->name('account.settings');
        Route::post('/bank/store','App\Http\Controllers\AccountController@bankDetails')->name('bank.store');
        Route::post('/document/store','App\Http\Controllers\AccountController@documentUpload')->name('document.store');

    Route::prefix('admin')->name('admin.')->middleware('can:admin')->group(function(){
        Route::get('/','App\Http\Controllers\AdminController@adminHome')->name('home');

        // Admin Leave Routes
        Route::get('/leaves','App\Http\Controllers\LeaveController@adminLeaves')->name('leaves');
        Route::get('/leave/reject/{leave}','App\Http\Controllers\LeaveController@rejectLeave')->name('leave.reject');
        Route::get('/leave/accept/{leave}','App\Http\Controllers\LeaveController@acceptLeave')->name('leave.accept');

        Route::get('/company','App\Http\Controllers\CompanyController@index')->name('company');
        Route::post('/company/save','App\Http\Controllers\CompanyController@store')->name('company.save');
        Route::post('/company/logo/upload','App\Http\Controllers\CompanyController@uploadImage')->name('company.logo.upload');
        Route::prefix('employees')->name('employees.')->group(function(){
            Route::get('/','App\Http\Controllers\AdminController@employees')->name('home');
            Route::get('/delete/{employee}','App\Http\Controllers\AdminController@employeeDestroy')->name('delete');
            Route::get('/{employee}','App\Http\Controllers\AdminController@employee')->name('show');
        });
        Route::prefix('users')->name('users.')->group(function(){
            Route::get('/','App\Http\Controllers\AdminController@users')->name('home');
            Route::post('/store','App\Http\Controllers\AdminController@userSave')->name('store');
            Route::get('/add','App\Http\Controllers\AdminController@userAdd')->name('add');
            Route::patch('/update/{user}','App\Http\Controllers\AdminController@userUpdate')->name('update');
            Route::get('/edit/{user}','App\Http\Controllers\AdminController@userAdd')->name('edit');
            Route::get('/delete/{user}','App\Http\Controllers\AdminController@userDestroy')->name('delete');
            Route::get('/activate/{user}','App\Http\Controllers\AdminController@userActivate')->name('activate');
            Route::get('/deactivate/{user}','App\Http\Controllers\AdminController@userDeactivate')->name('deactivate');
        });
        Route::prefix('category')->name('category.')->group(function(){
            Route::get('/','App\Http\Controllers\AdminController@category')->name('home');
            Route::post('/store','App\Http\Controllers\AdminController@categorySave')->name('store');
            Route::get('/add','App\Http\Controllers\AdminController@categoryAdd')->name('add');
            Route::patch('/update/{jobCategory}','App\Http\Controllers\AdminController@categoryUpdate')->name('update');
            Route::get('/edit/{jobCategory}','App\Http\Controllers\AdminController@categoryAdd')->name('edit');
            Route::get('/delete/{jobCategory}','App\Http\Controllers\AdminController@categoryDestroy')->name('delete');
        });
        Route::prefix('jobs')->name('jobs.')->group(function(){
            Route::get('/','App\Http\Controllers\AdminController@jobs')->name('home');
            Route::get('/add','App\Http\Controllers\AdminController@jobAdd')->name('add');
            Route::post('/store','App\Http\Controllers\AdminController@jobSave')->name('store');
            Route::patch('/update/{job}','App\Http\Controllers\AdminController@jobUpdate')->name('update');
            Route::get('/edit/{job}','App\Http\Controllers\AdminController@jobAdd')->name('edit');
            Route::get('/delete/{job}','App\Http\Controllers\AdminController@jobDestroy')->name('delete');
            Route::get('/applications','App\Http\Controllers\AdminController@applications')->name('applications');
            Route::get('/{job}/applications','App\Http\Controllers\AdminController@jobApplications')->name('applications.specific');
            Route::get('/applications/delete/{jobApplication}','App\Http\Controllers\AdminController@jobAppDestroy')->name('applications.delete');
            Route::get('/applications/accept/{jobApplication}','App\Http\Controllers\AdminController@jobAppAccept')->name('applications.accept');
            Route::get('/applications/reject/{jobApplication}','App\Http\Controllers\AdminController@jobAppReject')->name('applications.reject');
            Route::get('/candidates','App\Http\Controllers\AdminController@jobCandidates')->name('candidates');
        });
    });
});

Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;
    protected $primaryKey = 'user_id';
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'fname', 'mname', 'lname', 'email', 'password', 'tel', 'hear',  'gender', 'password', 'status', 'level',
    ];




    public function roles(){
        return $this->belongsToMany(Role::class, 'role_user', 'user_id');
    }
    public function employee(){
        return $this->hasOne('App\Models\Employee', 'user_id');
    }
    public function jobassigned(){
        return $this->hasMany('App\Models\JobAssigned', 'user_id');
    }
    public function application()
    {
        return $this->hasMany('App\Models\JobApplication', 'user_id');
    }

    public function job(){
        return $this->hasMany('App\Models\Job', 'user_id');
    }

    public function leave(){
        return $this->hasMany('App\Models\Leave', 'user_id');
    }
    public function education(){
        return $this->hasMany('App\Models\EmployeeEducation', 'user_id');
    }
    public function work_history(){
        return $this->hasMany('App\Models\EmployeeWorkHistory', 'user_id');
    }
    public function reference(){
        return $this->hasMany('App\Models\EmployeeReference', 'user_id');
    }

    public function bank(){
        return $this->hasOne('App\Models\BankDetails', 'user_id');
    }

    public function documents(){
        return $this->hasOne('App\Models\EmployeeDocuments', 'user_id');
    }

    public function company(){
        return $this->hasOne('App\Models\Company', 'user_id');
    }

    public function name()
    {
        return $this->fname.' '.$this->mname.' '.$this->lname;
    }

    public function isOwner($owner)
    {
        if ($this->user_id == $owner) {
            return true;
        }else{
            return false;
        }
    }

    public function avatar(){
        if ($this->gender == 'm') {
            return asset('/avatars/male.png');
        } else {
            return asset('/avatars/female.png');
        }
    }
    public static function Role()
    {
        # code...
        if(\Auth::user()){
            $role = \Auth::user()->user_level;
            return $role;
        }else{
            return false;
        }
    }
    public function isAdmin()
    {
        # code...
        if(\Auth::check()){
            if (\Auth::user()->level == 1) {
                return true;
            } else {
                return false;
            }
        }else{
            return false;
        }
    }
    public function isEmployee()
    {
        # code...
        if(\Auth::check()){
            if ($this->isAdmin()) {
                return true;
            }else{
                if (\Auth::user()->level == 0 && \Auth::user()->employee()->exists()) {
                    return true;
                } else {
                    return false;
                }
            }
        }else{
            return false;
        }
    }
    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function isSuper()
    {
        if ($this->level > 1){
            return true;
        }
        return false;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function dashboard()
    {
        return view('users.index');
    }

    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
}

resources/views/admin/users/index.blade.php
@extends('layouts.master')
@section('title', 'Manage Users')
@section('content')
    @include('inc.breadcrumb')
    <div class="manage-jobs section">
        <div class="container">
            <div class="alerts-inner">
                <div class="row">
                    @include('inc.dashboard.sidebar')
                    <div class="col-lg-8 col-12">
                        @include('inc.dashboard.alert')
                        <div class="job-items">
                            @if(count($users) > 0)
                                <div class="manage-list">
                                    <div class="row">
                                        <div class="col-lg-3 col-md-3 col-12">
                                            <p>Full Name</p>
                                        </div>
                                        <div class="col-lg-3 col-md-3 col-12">
                                            <p>Telephone</p>
                                        </div>
                                        <div class="col-lg-3 col-md-3 col-12">
                                            <p>Status</p>
                                        </div>
                                        <div class="col-lg-3 col-md-3 col-12">
                                            <p>Actions</p>
                                        </div>
                                    </div>
                                </div>
                            @endif
                            @forelse($users as $user)
                                <div class="manage-content">
                                    <div class="row align-items-center justify-content-center">
                                        <div class="col-lg-3 col-md-3 col-12">
                                            <h3>{{ $user->name() }}<span><small>{{ $user->email }}</small></span></h3>
                                        </div>
                                        <div class="col-lg-3 col-md-3 col-12">
                                            <p><span class="time">{{ $user->tel }}</span></p>
                                        </div>
                                        <div class="col-lg-1 col-md-1 col-12">
                                            <p>
                                                @if($user->status == '1')
                                                    Active
                                                @else
                                                    Inactive
                                                @endif
                                            </p>
                                        </div>
                                        <div class="col-lg-5 col-md-5 col-12">
                                            <p>
                                                <a href="{{ route('dashboard.admin.users.edit', $user->user_id) }}" class="mx-2"><i class="lni lni-pencil"></i> Edit</a>
                                                @if($user->status == '1')
                                                    <a href="{{ route('dashboard.admin.users.deactivate', $user->user_id) }}"><i class="lni lni-close"></i> Deactivate</a>
                                                @else
                                                    <a href="{{ route('dashboard.admin.users.activate', $user->user_id) }}"><i class="lni lni-eye"></i> Activate</a>
                                                @endif
                                                <a href="{{ route('dashboard.admin.users.delete', $user->user_id) }}" onclick="return confirm('Are you sure you want to delete this user?');" class="delete mx-2"><i class="lni lni-trash"></i> Delete</a>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            @empty
                                <div class="manage-content">
                                    <div class="row align-items-center justify-content-center">
                                        <div class="col-lg-12 col-12">
                                            <h3>Oops!! No Users Found.</h3>
                                        </div>
                                    </div>
                                </div>
                            @endforelse
                        </div>

                        <div class="pagination left pagination-md-center">
                            <ul class="pagination-list">
                                {!! $users->links() !!}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Dashboard -->
    <div id="dashboard">

        <!-- Navigation
        ================================================== -->
    @include('inc.dashboard.sidebar')
    <!-- Content
	================================================== -->
        <div class="dashboard-content">
            @include('inc.dashboard.breadcrumb')


            <div class="row">

                <!-- Table-->
                <div class="col-lg-12 col-md-12">

                    @include('inc.dashboard.alert')
                    <div class="dashboard-list-box margin-top-30">
                        <div class="dashboard-list-box-content">

                            <!-- Table -->

                            <table class="manage-table responsive-table">
                                @if(count($users) > 0)
                                    <tr>
                                        <th><i class="fa fa-file-text"></i> Full Name</th>
                                        <th><i class="fa fa-mail-reply"></i>Email</th>
                                        <th><i class="fa fa-calendar"></i> Status</th>
                                        <th><i class="fa fa-calendar"></i> Date Joined</th>
                                        <th><i class="fa fa-user"></i> Level</th>
                                        <th></th>
                                    </tr>
                                @endif
                                @forelse($users as $user)
                                <!-- Item #2 -->
                                    <tr>
                                        <td class="title">
                                            <a href="#">{{ $user->fname }} @isset($user->mname) {{ $user->mname }} @endisset @isset($user->lname) {{ $user->lname }} @endisset</a>
                                        </td>
                                        <td class="centered">{{ $user->email }}</td>
                                        <td>
                                            @if($user->status == '1')
                                                Active
                                            @else
                                                Inactive
                                            @endif
                                        </td>
                                        <td>{{ $user->created_at->format('dS M, Y') }}</td>
                                        <td class="centered">
                                            @if($user->level > 0)
                                                Admin
                                            @else
                                                User
                                            @endif
                                        </td>
                                        <td class="action">
                                            <a href="{{ route('dashboard.admin.users.edit', $user->user_id) }}"><i class="fa fa-pencil"></i> Edit</a>
                                            @if($user->status == '1')
                                                <a href="{{ route('dashboard.admin.users.deactivate', $user->user_id) }}"><i class="fa  fa-eye-slash"></i> Deactivate</a>
                                            @else
                                                <a href="{{ route('dashboard.admin.users.activate', $user->user_id) }}"><i class="fa  fa-eye-slash"></i> Activate</a>
                                            @endif
                                            <a href="{{ route('dashboard.admin.users.delete', $user->user_id) }}" onclick="return confirm('Are you sure you want to delete this job?');" class="delete"><i class="fa fa-remove"></i> Delete</a>
                                        </td>
                                    </tr>
                                @empty

                                <!-- Item #2 -->
                                    <tr>
                                        <td class="title"><a href="#">Oops!! No Users Found.</a></td>
                                    </tr>
                                @endforelse


                            </table>

                        </div>
                    </div>
                </div>

                @include('inc.dashboard.footer')
            </div>

        </div>
        <!-- Content / End -->

    </div>
    <!-- Dashboard / End -->
@endsection